import { createClient } from '@/lib/supabase/server'
import { createClient as createAdmin } from '@supabase/supabase-js'
import PDFDocument from 'pdfkit'

export const runtime = 'nodejs'

// ── Contract PDF renderer ──────────────────────────────────────────────────
// Renders AI-generated contract text as a professional legal PDF.
async function generateContractPdf(opts: {
  refNumber: string
  issueDate: string
  buyerName: string
  supplierName: string
  contractText: string
}): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const ML = 60          // margin
    const MT = 55
    const PW = 612
    const PH = 792
    const CW = PW - ML * 2  // 492

    const doc = new (PDFDocument as any)({
      size: 'LETTER',
      margins: { top: MT, bottom: 55, left: ML, right: ML },
      info: {
        Title: `Trade Agreement ${opts.refNumber}`,
        Author: 'Strike SCF',
        Creator: 'Strike SCF AI',
        Subject: 'Commercial Trade Agreement',
      },
      autoFirstPage: true,
    }) as PDFKit.PDFDocument

    const chunks: Buffer[] = []
    doc.on('data', (c: Buffer) => chunks.push(c))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    let y = MT

    // ── HEADER ──
    doc.rect(ML, y, 3, 58).fill(BLUE)

    doc.font('Helvetica-Bold').fontSize(17).fillColor(BLUE)
      .text('COMMERCIAL TRADE AGREEMENT', ML + 10, y + 2, { width: CW - 10, lineBreak: false })
    doc.font('Helvetica').fontSize(9).fillColor(GRAY)
      .text(`Reference: ${opts.refNumber}`, ML + 10, y + 24, { width: CW / 2, lineBreak: false })
    doc.font('Helvetica').fontSize(9).fillColor(GRAY)
      .text(`Date: ${opts.issueDate}`, ML + 10, y + 36, { width: CW / 2, lineBreak: false })
    doc.font('Helvetica-Bold').fontSize(8).fillColor(GRAY)
      .text('Generated by Strike SCF AI', ML + 10, y + 48, { width: CW / 2, lineBreak: false })

    y += 68

    doc.moveTo(ML, y).lineTo(ML + CW, y).strokeColor(BLUE).lineWidth(1).stroke()
    y += 14

    // ── PARTIES ──
    const halfW = Math.floor((CW - 10) / 2)

    doc.rect(ML, y, halfW, 60).fill(LIGHT)
    doc.font('Helvetica-Bold').fontSize(6.5).fillColor(BLUE)
      .text('BUYER', ML + 8, y + 8, { width: halfW - 16, lineBreak: false })
    doc.font('Helvetica-Bold').fontSize(11).fillColor(DARK)
      .text(opts.buyerName, ML + 8, y + 20, { width: halfW - 16 })

    const rx = ML + halfW + 10
    doc.rect(rx, y, halfW, 60).fill(ALT_BG)
    doc.rect(rx, y, 3, 60).fill(BLUE)
    doc.font('Helvetica-Bold').fontSize(6.5).fillColor(BLUE)
      .text('SELLER / SUPPLIER', rx + 10, y + 8, { width: halfW - 18, lineBreak: false })
    doc.font('Helvetica-Bold').fontSize(11).fillColor(DARK)
      .text(opts.supplierName, rx + 10, y + 20, { width: halfW - 18 })

    y += 74

    doc.moveTo(ML, y).lineTo(ML + CW, y).strokeColor(BORDER).lineWidth(0.5).stroke()
    y += 16

    // ── CONTRACT BODY ──
    // Each section: detect ALL-CAPS headers vs body paragraphs
    const paragraphs = opts.contractText.split(/\n{2,}/).map(p => p.trim()).filter(Boolean)

    paragraphs.forEach(para => {
      const lines = para.split('\n')
      const firstLine = (lines[0] ?? '').trim()
      // Detect section header: all caps or ends with colon + short
      const isHeader = /^[A-Z][A-Z\s\d.:&/-]{3,}$/.test(firstLine) || /^[A-Z\s]{4,}:/.test(firstLine)

      if (isHeader) {
        doc.font('Helvetica-Bold').fontSize(9).fillColor(BLUE)
          .text(firstLine, ML, y, { width: CW })
        y = doc.y + 3
        const rest = lines.slice(1).join('\n').trim()
        if (rest) {
          doc.font('Helvetica').fontSize(9).fillColor(DARK)
            .text(rest, ML, y, { width: CW })
          y = doc.y + 8
        }
      } else {
        doc.font('Helvetica').fontSize(9).fillColor(DARK)
          .text(para, ML, y, { width: CW })
        y = doc.y + 8
      }
    })

    // ── FOOTER (every page) ──
    const range = doc.bufferedPageRange()
    for (let i = 0; i < range.count; i++) {
      doc.switchToPage(range.start + i)
      const FY = PH - 55 - 22
      doc.moveTo(ML, FY).lineTo(ML + CW, FY).strokeColor('#E5E7EB').lineWidth(0.4).stroke()
      doc.font('Helvetica').fontSize(7).fillColor(GRAY)
        .text('Confidential · Generated by Strike SCF AI · strikescf.com', ML, FY + 6, { width: CW / 2, lineBreak: false })
      doc.font('Helvetica').fontSize(7).fillColor(GRAY)
        .text(`Page ${i + 1} of ${range.count}`, ML + CW / 2, FY + 6, { width: CW / 2, align: 'right', lineBreak: false })
    }

    doc.end()
  })
}

const adminClient = createAdmin(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

// ── Brand palette ──────────────────────────────────────────────────────────
const BLUE    = '#1428CC'
const DARK    = '#111827'
const MEDIUM  = '#374151'
const GRAY    = '#9CA3AF'
const LIGHT   = '#F3F4F6'
const ALT_BG  = '#EEF0FF'
const WHITE   = '#FFFFFF'
const BORDER  = '#CBD5E1'

// ── Helpers ────────────────────────────────────────────────────────────────
function fmtCurrency(n: number | null | undefined, currency = 'USD'): string {
  if (n == null) return '—'
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency,
    maximumFractionDigits: 2,
  }).format(n)
}

function todayStr(): string {
  return new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })
}

function dueDateStr(paymentTerms?: string | null): string {
  const match = paymentTerms?.match(/(\d+)/)
  const days = match?.[1] ? parseInt(match[1], 10) : 30
  const d = new Date()
  d.setDate(d.getDate() + days)
  return d.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
}

function orgAddress(org: Record<string, any> | null): string {
  if (!org) return ''
  const parts = [
    org.address_line1,
    org.city,
    org.state,
    org.country_of_origin,
  ].filter(Boolean)
  return parts.join(', ')
}

interface LineItem {
  name?: string | null
  description?: string | null
  quantity?: number | null
  unit?: string | null
  unit_price?: number | null
  currency?: string | null
}

// ── PDF generator ─────────────────────────────────────────────────────────
function generatePdf(opts: {
  docType: 'po' | 'invoice'
  refNumber: string
  issueDate: string
  dueDate: string
  buyer: { name: string; address: string }
  supplier: { name: string; address: string }
  lineItems: LineItem[]
  totalValue: number
  currency: string
  paymentTerms: string
  incoterms: string
  deliveryDate: string
  deliveryLocation?: string | null
  goodsDescription?: string | null
}): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const ML = 50          // left/right margin
    const MT = 50          // top margin
    const PW = 612         // Letter width
    const PH = 792         // Letter height
    const CW = PW - ML * 2 // content width = 512

    const doc = new (PDFDocument as any)({
      size: 'LETTER',
      margins: { top: MT, bottom: 50, left: ML, right: ML },
      info: {
        Title: opts.docType === 'po'
          ? `Purchase Order ${opts.refNumber}`
          : `Commercial Invoice ${opts.refNumber}`,
        Author: 'Strike SCF',
        Creator: 'Strike SCF AI',
        Subject: opts.docType === 'po' ? 'Purchase Order' : 'Commercial Invoice',
      },
      autoFirstPage: true,
    }) as PDFKit.PDFDocument

    const chunks: Buffer[] = []
    doc.on('data', (c: Buffer) => chunks.push(c))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    const isPO      = opts.docType === 'po'
    const docLabel  = isPO ? 'PURCHASE ORDER' : 'COMMERCIAL INVOICE'
    const issuer    = isPO ? opts.buyer    : opts.supplier
    const recipient = isPO ? opts.supplier : opts.buyer

    let y = MT

    // ── HEADER ────────────────────────────────────────────────────────────
    // Left accent bar
    doc.rect(ML, y, 3, 66).fill(BLUE)

    // Issuer block (left)
    doc.font('Helvetica-Bold').fontSize(14).fillColor(DARK)
      .text(issuer.name, ML + 10, y + 2, { width: 265, lineBreak: false })
    doc.font('Helvetica').fontSize(8).fillColor(GRAY)
      .text(issuer.address || 'Address on file', ML + 10, y + 20, { width: 265, lineBreak: false })
    doc.font('Helvetica').fontSize(7.5).fillColor(GRAY)
      .text('strikescf.com', ML + 10, y + 32, { width: 265, lineBreak: false })

    // Document label (right)
    doc.font('Helvetica-Bold').fontSize(16).fillColor(BLUE)
      .text(docLabel, ML + 275, y, { width: CW - 275, align: 'right', lineBreak: false })
    doc.font('Helvetica-Bold').fontSize(9).fillColor(DARK)
      .text(opts.refNumber, ML + 275, y + 23, { width: CW - 275, align: 'right', lineBreak: false })
    doc.font('Helvetica').fontSize(8.5).fillColor(GRAY)
      .text(`Date: ${opts.issueDate}`, ML + 275, y + 36, { width: CW - 275, align: 'right', lineBreak: false })

    y += 76

    // Thick blue separator line
    doc.moveTo(ML, y).lineTo(ML + CW, y).strokeColor(BLUE).lineWidth(1.5).stroke()
    y += 14

    // ── INFO BAND ─────────────────────────────────────────────────────────
    doc.rect(ML, y, CW, 40).fill(LIGHT)

    const infoItems: [string, string][] = isPO
      ? [
          ['PO NUMBER', opts.refNumber],
          ['ISSUE DATE', opts.issueDate],
          ['DELIVERY DATE', opts.deliveryDate],
          ['INCOTERMS', opts.incoterms],
        ]
      : [
          ['INVOICE NO.', opts.refNumber],
          ['ISSUE DATE', opts.issueDate],
          ['PAYMENT DUE', opts.dueDate],
          ['INCOTERMS', opts.incoterms],
        ]

    const iCW = CW / 4
    infoItems.forEach(([lbl, val], i) => {
      const ix = ML + i * iCW + 9
      doc.font('Helvetica-Bold').fontSize(6.5).fillColor(GRAY)
        .text(lbl, ix, y + 8, { width: iCW - 12, lineBreak: false })
      doc.font('Helvetica-Bold').fontSize(9).fillColor(DARK)
        .text(val, ix, y + 18, { width: iCW - 12, lineBreak: false })
    })

    y += 54

    // ── PARTIES ───────────────────────────────────────────────────────────
    const halfW = Math.floor((CW - 12) / 2)

    // Issuer box
    doc.rect(ML, y, halfW, 76).fill(LIGHT)
    doc.font('Helvetica-Bold').fontSize(6.5).fillColor(BLUE)
      .text(isPO ? 'BUYER' : 'SELLER / INVOICE FROM', ML + 9, y + 9, { width: halfW - 18, lineBreak: false })
    doc.font('Helvetica-Bold').fontSize(11).fillColor(DARK)
      .text(issuer.name, ML + 9, y + 21, { width: halfW - 18 })
    doc.font('Helvetica').fontSize(8).fillColor(MEDIUM)
      .text(issuer.address || '—', ML + 9, y + 37, { width: halfW - 18 })

    // Recipient box
    const rx = ML + halfW + 12
    doc.rect(rx, y, halfW, 76).fill(ALT_BG)
    doc.rect(rx, y, 3, 76).fill(BLUE)
    doc.font('Helvetica-Bold').fontSize(6.5).fillColor(BLUE)
      .text(isPO ? 'SUPPLIER / SHIP FROM' : 'BUYER / BILL TO', rx + 10, y + 9, { width: halfW - 18, lineBreak: false })
    doc.font('Helvetica-Bold').fontSize(11).fillColor(DARK)
      .text(recipient.name, rx + 10, y + 21, { width: halfW - 18 })
    doc.font('Helvetica').fontSize(8).fillColor(MEDIUM)
      .text(recipient.address || '—', rx + 10, y + 37, { width: halfW - 18 })

    y += 90

    // ── LINE ITEMS TABLE ──────────────────────────────────────────────────
    // Column layout (total = CW = 512)
    const C = {
      num:   { x: ML,       w: 22  },  // 50–72
      desc:  { x: ML + 22,  w: 196 },  // 72–268
      qty:   { x: ML + 218, w: 54  },  // 268–322
      unit:  { x: ML + 272, w: 54  },  // 322–376
      price: { x: ML + 326, w: 88  },  // 376–464
      amt:   { x: ML + 414, w: 98  },  // 464–562 = ML+CW ✓
    }

    // Header
    const TH = 22
    doc.rect(ML, y, CW, TH).fill(BLUE)

    const headers: Array<[keyof typeof C, string, 'left' | 'right' | 'center']> = [
      ['num',   '#',           'center'],
      ['desc',  'DESCRIPTION', 'left'],
      ['qty',   'QTY',         'right'],
      ['unit',  'UNIT',        'right'],
      ['price', 'UNIT PRICE',  'right'],
      ['amt',   'AMOUNT',      'right'],
    ]

    headers.forEach(([col, label, align]) => {
      const c = C[col]
      doc.font('Helvetica-Bold').fontSize(7.5).fillColor(WHITE)
        .text(label, c.x + 3, y + 7, { width: c.w - 6, align, lineBreak: false })
    })

    y += TH

    // Rows
    const rows = opts.lineItems.length > 0
      ? opts.lineItems.map(li => {
          const rawAmt =
            li.quantity != null && li.unit_price != null
              ? li.quantity * li.unit_price
              : null
          return {
            desc:    li.name || li.description || 'Item',
            qty:     li.quantity != null ? li.quantity.toLocaleString() : '—',
            unit:    li.unit || '—',
            price:   li.unit_price != null
              ? fmtCurrency(li.unit_price, li.currency ?? opts.currency)
              : '—',
            amt:     rawAmt != null
              ? fmtCurrency(rawAmt, li.currency ?? opts.currency)
              : '—',
            rawAmt,
          }
        })
      : [{
          desc:   opts.goodsDescription || 'Trade Goods',
          qty:    '—',
          unit:   '—',
          price:  '—',
          amt:    fmtCurrency(opts.totalValue, opts.currency),
          rawAmt: opts.totalValue,
        }]

    let subtotal = 0
    rows.forEach((row, i) => {
      const RH = 22
      if (i % 2 === 1) doc.rect(ML, y, CW, RH).fill(LIGHT)

      doc.font('Helvetica').fontSize(8.5).fillColor(DARK)
        .text(String(i + 1), C.num.x + 3,   y + 6, { width: C.num.w   - 6, align: 'center', lineBreak: false })
        .text(row.desc,       C.desc.x + 3,  y + 6, { width: C.desc.w  - 6, align: 'left',   lineBreak: false })
        .text(row.qty,        C.qty.x + 3,   y + 6, { width: C.qty.w   - 6, align: 'right',  lineBreak: false })
        .text(row.unit,       C.unit.x + 3,  y + 6, { width: C.unit.w  - 6, align: 'right',  lineBreak: false })
        .text(row.price,      C.price.x + 3, y + 6, { width: C.price.w - 6, align: 'right',  lineBreak: false })
        .text(row.amt,        C.amt.x + 3,   y + 6, { width: C.amt.w   - 6, align: 'right',  lineBreak: false })

      if (row.rawAmt != null) subtotal += row.rawAmt
      y += RH
    })

    if (subtotal === 0) subtotal = opts.totalValue

    // Table bottom border
    doc.moveTo(ML, y).lineTo(ML + CW, y).strokeColor(BORDER).lineWidth(0.5).stroke()
    y += 14

    // ── TOTALS BOX ────────────────────────────────────────────────────────
    const TBX = ML + CW - 180
    const TBW = 180

    doc.rect(TBX, y, TBW, 66).fill(LIGHT)

    doc.font('Helvetica').fontSize(8.5).fillColor(MEDIUM)
      .text('Subtotal', TBX + 9, y + 9, { width: 80, lineBreak: false })
    doc.font('Helvetica').fontSize(8.5).fillColor(DARK)
      .text(fmtCurrency(subtotal, opts.currency), TBX + 9, y + 9, { width: TBW - 18, align: 'right', lineBreak: false })

    doc.font('Helvetica').fontSize(8.5).fillColor(MEDIUM)
      .text('Tax / VAT', TBX + 9, y + 25, { width: 80, lineBreak: false })
    doc.font('Helvetica').fontSize(8.5).fillColor(DARK)
      .text(fmtCurrency(0, opts.currency), TBX + 9, y + 25, { width: TBW - 18, align: 'right', lineBreak: false })

    doc.moveTo(TBX + 9, y + 42).lineTo(TBX + TBW - 9, y + 42).strokeColor(BORDER).lineWidth(0.5).stroke()

    doc.font('Helvetica-Bold').fontSize(10).fillColor(DARK)
      .text('TOTAL', TBX + 9, y + 48, { width: 80, lineBreak: false })
    doc.font('Helvetica-Bold').fontSize(10).fillColor(BLUE)
      .text(fmtCurrency(opts.totalValue, opts.currency), TBX + 9, y + 48, { width: TBW - 18, align: 'right', lineBreak: false })

    y += 82

    // ── TERMS ─────────────────────────────────────────────────────────────
    const termsTitle = isPO ? 'TERMS & CONDITIONS' : 'PAYMENT INSTRUCTIONS'
    doc.font('Helvetica-Bold').fontSize(7.5).fillColor(BLUE)
      .text(termsTitle, ML, y, { width: CW, lineBreak: false })
    doc.moveTo(ML, y + 13).lineTo(ML + CW, y + 13).strokeColor(BLUE).lineWidth(0.75).stroke()
    y += 20

    const termsItems: [string, string][] = [
      ['Payment Terms', opts.paymentTerms],
      ['Incoterms',     opts.incoterms],
      ['Delivery Date', opts.deliveryDate],
      ...(opts.deliveryLocation ? [['Delivery Location', opts.deliveryLocation] as [string, string]] : []),
    ]

    const tCount = Math.min(termsItems.length, 4)
    const tCW = CW / tCount
    termsItems.slice(0, 4).forEach(([lbl, val], i) => {
      doc.font('Helvetica-Bold').fontSize(7).fillColor(GRAY)
        .text(lbl.toUpperCase(), ML + i * tCW, y, { width: tCW - 10, lineBreak: false })
      doc.font('Helvetica').fontSize(9).fillColor(DARK)
        .text(val, ML + i * tCW, y + 13, { width: tCW - 10, lineBreak: false })
    })

    y += 36

    if (!isPO) {
      // Bank details note for invoices
      doc.font('Helvetica-Bold').fontSize(7).fillColor(GRAY)
        .text('REMITTANCE', ML, y, { width: CW, lineBreak: false })
      doc.font('Helvetica').fontSize(8.5).fillColor(MEDIUM)
        .text(
          'Remit payment to the bank account specified in the financing agreement, or contact your Strike SCF account manager.',
          ML, y + 13,
          { width: CW }
        )
      y += 38
    }

    y += 8

    // ── SIGNATURE BLOCKS ──────────────────────────────────────────────────
    const sigW = Math.floor((CW - 20) / 2)
    const sig1 = isPO ? 'AUTHORIZED BY (BUYER)'      : 'ISSUED BY (SELLER)'
    const sig2 = isPO ? 'ACKNOWLEDGED BY (SUPPLIER)' : 'RECEIVED BY (BUYER)'

    ;([
      [ML,              sig1],
      [ML + sigW + 20,  sig2],
    ] as const).forEach(([x, lbl]) => {
      doc.font('Helvetica-Bold').fontSize(7).fillColor(GRAY)
        .text(lbl, x, y, { width: sigW, lineBreak: false })

      // Signature box
      doc.rect(x, y + 13, sigW, 30).strokeColor(BORDER).lineWidth(0.5).stroke()
      doc.font('Helvetica').fontSize(7).fillColor(BORDER)
        .text('Signature', x + 5, y + 23, { width: sigW - 10, lineBreak: false })

      const fieldY = y + 50
      doc.font('Helvetica').fontSize(8).fillColor(MEDIUM)
        .text('Name:', x, fieldY, { width: 38, lineBreak: false })
      doc.moveTo(x + 42, fieldY + 9).lineTo(x + sigW, fieldY + 9).strokeColor(BORDER).lineWidth(0.4).stroke()

      doc.font('Helvetica').fontSize(8).fillColor(MEDIUM)
        .text('Title:', x, fieldY + 16, { width: 38, lineBreak: false })
      doc.moveTo(x + 42, fieldY + 25).lineTo(x + sigW, fieldY + 25).strokeColor(BORDER).lineWidth(0.4).stroke()

      doc.font('Helvetica').fontSize(8).fillColor(MEDIUM)
        .text('Date:', x, fieldY + 32, { width: 38, lineBreak: false })
      doc.moveTo(x + 42, fieldY + 41).lineTo(x + sigW, fieldY + 41).strokeColor(BORDER).lineWidth(0.4).stroke()
    })

    y += 106

    // ── FOOTER (pinned near bottom) ───────────────────────────────────────
    const FY = PH - 50 - 26

    doc.moveTo(ML, FY).lineTo(ML + CW, FY).strokeColor('#E5E7EB').lineWidth(0.5).stroke()

    doc.font('Helvetica').fontSize(7.5).fillColor(GRAY)
      .text(
        'Generated by Strike SCF AI · Confidential · For authorized parties only',
        ML, FY + 7,
        { width: CW / 2, lineBreak: false }
      )

    doc.font('Helvetica-Bold').fontSize(7.5).fillColor(BLUE)
      .text('✦ strikescf.com', ML + CW / 2, FY + 7, { width: CW / 2, align: 'right', lineBreak: false })

    doc.font('Helvetica').fontSize(7).fillColor(GRAY)
      .text('Page 1 of 1', ML + CW / 2, FY + 17, { width: CW / 2, align: 'right', lineBreak: false })

    doc.end()
  })
}

// ── Route handler ─────────────────────────────────────────────────────────
export async function POST(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params

  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 })

  const { data: userData } = await adminClient
    .from('users')
    .select('id, role, org_id')
    .eq('id', user.id)
    .single()
  if (!userData) return Response.json({ error: 'User not found' }, { status: 401 })

  let body: { type: 'po' | 'invoice' | 'contract' }
  try { body = await request.json() }
  catch { return Response.json({ error: 'Invalid JSON' }, { status: 400 }) }

  const { type } = body
  if (type !== 'po' && type !== 'invoice' && type !== 'contract') {
    return Response.json({ error: 'type must be po, invoice, or contract' }, { status: 400 })
  }

  const { data: deal } = await adminClient
    .from('deals')
    .select('*')
    .eq('id', id)
    .single()
  if (!deal) return Response.json({ error: 'Deal not found' }, { status: 404 })

  const isBankUser = ['bank_admin', 'bank_credit_officer'].includes(userData.role)
  const isParty    = deal.buyer_org_id === userData.org_id || deal.supplier_org_id === userData.org_id
  if (!isParty && !isBankUser) {
    return Response.json({ error: 'Forbidden' }, { status: 403 })
  }

  // ── Contract PDF (fetch stored text → render as PDF) ──────────────────────
  if (type === 'contract') {
    const contractDocId = (deal as any).contract_document_id
    if (!contractDocId) {
      return Response.json({ error: 'No contract document found for this deal' }, { status: 404 })
    }

    const { data: contractDoc } = await adminClient
      .from('documents')
      .select('storage_path')
      .eq('id', contractDocId)
      .single()
    if (!contractDoc) return Response.json({ error: 'Contract document record not found' }, { status: 404 })

    const { data: fileData, error: dlErr } = await adminClient.storage
      .from('deal-documents')
      .download(contractDoc.storage_path)
    if (dlErr || !fileData) return Response.json({ error: 'Failed to retrieve contract file' }, { status: 500 })

    const contractText = await fileData.text()

    const [buyerRes, supplierRes] = await Promise.all([
      adminClient.from('organizations').select('legal_name, doing_business_as').eq('id', deal.buyer_org_id).single(),
      adminClient.from('organizations').select('legal_name, doing_business_as').eq('id', deal.supplier_org_id).single(),
    ])

    const pdfBuf = await generateContractPdf({
      refNumber:    `STRIKE-AGR-${id.slice(0, 8).toUpperCase()}`,
      issueDate:    todayStr(),
      buyerName:    buyerRes.data?.doing_business_as || buyerRes.data?.legal_name || 'Buyer',
      supplierName: supplierRes.data?.doing_business_as || supplierRes.data?.legal_name || 'Supplier',
      contractText,
    })

    return new Response(new Uint8Array(pdfBuf), {
      status: 200,
      headers: {
        'Content-Type':        'application/pdf',
        'Content-Disposition': `attachment; filename="trade-agreement-${id.slice(0, 8).toUpperCase()}.pdf"`,
        'Content-Length':      String(pdfBuf.length),
      },
    })
  }

  const [buyerRes, supplierRes, lineItemsRes] = await Promise.all([
    adminClient
      .from('organizations')
      .select('legal_name, doing_business_as, address_line1, city, state, country_of_origin')
      .eq('id', deal.buyer_org_id)
      .single(),
    adminClient
      .from('organizations')
      .select('legal_name, doing_business_as, address_line1, city, state, country_of_origin')
      .eq('id', deal.supplier_org_id)
      .single(),
    deal.listing_id
      ? adminClient
          .from('listing_line_items')
          .select('name, description, quantity, unit, unit_price, currency')
          .eq('listing_id', deal.listing_id)
      : Promise.resolve({ data: [] as any[] }),
  ])

  const buyer     = buyerRes.data
  const supplier  = supplierRes.data
  const lineItems: LineItem[] = (lineItemsRes as any).data ?? []

  const dealId8   = id.slice(0, 8).toUpperCase()
  const currency  = deal.agreed_currency ?? 'USD'
  const totalVal  = deal.total_value ?? deal.agreed_price ?? 0

  const refNumber = type === 'po'
    ? `STRIKE-PO-${dealId8}`
    : `STRIKE-INV-${dealId8}`

  const issueDate    = todayStr()
  const dueDate      = dueDateStr(deal.agreed_payment_terms)
  const paymentTerms = deal.agreed_payment_terms ?? 'Net 30'
  const incoterms    = deal.agreed_incoterms       ?? 'CIF'
  const delivDate    = deal.agreed_delivery_date
    ? new Date(deal.agreed_delivery_date).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
    : 'As agreed'

  const pdfBuffer = await generatePdf({
    docType:          type,
    refNumber,
    issueDate,
    dueDate,
    buyer:    { name: buyer?.doing_business_as || buyer?.legal_name || 'Buyer',       address: orgAddress(buyer) },
    supplier: { name: supplier?.doing_business_as || supplier?.legal_name || 'Supplier', address: orgAddress(supplier) },
    lineItems,
    totalValue:       totalVal,
    currency,
    paymentTerms,
    incoterms,
    deliveryDate:     delivDate,
    deliveryLocation: deal.delivery_location,
    goodsDescription: deal.goods_description,
  })

  const filename = type === 'po'
    ? `purchase-order-${dealId8}.pdf`
    : `commercial-invoice-${dealId8}.pdf`

  return new Response(new Uint8Array(pdfBuffer), {
    status: 200,
    headers: {
      'Content-Type':        'application/pdf',
      'Content-Disposition': `attachment; filename="${filename}"`,
      'Content-Length':      String(pdfBuffer.length),
    },
  })
}
