-- Hardens erp_connections.dispatch_token (ASSESSMENT.md P0-4): it was
-- generated by a DB column DEFAULT, stored and compared in plaintext, with
-- no expiry, scope, or revocation. This migration adds hash-based storage
-- alongside the existing plaintext column (kept, not dropped — see the
-- comment below) so existing tokens keep working without forcing every
-- connected org to reconnect.

ALTER TABLE erp_connections
  ADD COLUMN IF NOT EXISTS dispatch_token_hash TEXT,
  ADD COLUMN IF NOT EXISTS dispatch_token_prefix TEXT,
  ADD COLUMN IF NOT EXISTS dispatch_token_scopes TEXT[] NOT NULL DEFAULT ARRAY['*']::TEXT[],
  ADD COLUMN IF NOT EXISTS dispatch_token_expires_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS dispatch_token_revoked_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS dispatch_token_rotated_at TIMESTAMPTZ NOT NULL DEFAULT now();

-- Backfill: hash whatever plaintext token already exists so it keeps
-- authenticating after the app switches to hash-based lookup below.
UPDATE erp_connections
SET
  dispatch_token_hash = encode(digest(dispatch_token, 'sha256'), 'hex'),
  dispatch_token_prefix = left(dispatch_token, 8)
WHERE dispatch_token_hash IS NULL AND dispatch_token IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS erp_connections_dispatch_token_hash_idx
  ON erp_connections (dispatch_token_hash)
  WHERE dispatch_token_hash IS NOT NULL;

-- Stop the database from auto-generating a new plaintext token on future
-- inserts — app/api/erp/connect/route.ts now generates the raw token in
-- application code, stores only its hash, and returns the raw value once
-- in the API response (never persisted, never re-selectable). The
-- `dispatch_token` column itself is intentionally NOT dropped in this
-- migration: existing rows' plaintext values remain until those
-- connections are next rotated, which is an acceptable interim state for a
-- pre-launch product with no production customers, but should be purged in
-- a follow-up migration once confirmed nothing depends on it (see
-- docs/enterprise-readiness/ROADMAP.md 1.G).
ALTER TABLE erp_connections
  ALTER COLUMN dispatch_token DROP DEFAULT,
  ALTER COLUMN dispatch_token DROP NOT NULL;
